"""MVP feature types from model_learn.py."""
from __future__ import annotations

# Исторические pivot-колонки RECOVERED*_{1..5} (если попадут в датасет — утечка).
_TARGET_SEV_RECOVERED_COLS: tuple[str, ...] = tuple(
    f"{prefix}_{instance}"
    for prefix in (
        "RECOVEREDMAINDEBT",
        "RECOVEREDWEAROUT",
        "RECOVEREDLOSSCOMMODYVALUE",
        "RECOVEREDVALUEWITHSD",
    )
    for instance in range(1, 6)
)

DEFAULT_MVP_INPUT_TYPES: dict[str, list[str]] = {'NUMERIC': ['LONGITUDE', 'LATITUDE'],
 'CATEGORIAL': [],
 'TO_DROP': ['Сумма_взыскано_по_ФУ',
             'Суммы_взыскано_по_иску',
             'Общая_сумма_заявленных_требований_ФУ',
             'Доп_расходы_инцидент',
             'Общая_сумма_заявленных_требований_ИСК',
             'Номер_инциндента',
             'UTSSurchargeValue_cumsum_by_incident_all',
             'SurchargeValue_cumsum_by_incident_all',
             'SurchargeValue_cumsum_by_incident',
             'UTSSurchargeValue_cumsum_by_incident',
             'Сумма_утс',
             *list(_TARGET_SEV_RECOVERED_COLS),
             'PAYMENT_VALUE',
             'Сумма_выплат_по_претензиям',
             'FIN',
             'VICTIM_LOSS_SUM_FUTURE',
             'GUILTY_LOSS_SUM_FUTURE',
             'REFUND_FORM_INCIDENT',
             'PAYMENTS_SUM_RUR',
             'VICTIM_LOSS_COUNT_FUTURE',
             'FIX',
             'GUILTY_LOSS_COUNT_FUTURE',
             'LOSS_AMOUNT',
             'Выплата_по_основному_убытку',
             'Взысканный_износ_ИСК',
             'REFUND_FORM_INCIDENT',
             'EVENT_NUMBER',
             'PREMIUM_SUM_FUTURE_ALL',
             'OSAGO_FL_2022_PVU_FREQUENCY_osago',
             'OSAGO_FL_2022_PVU_PVU_RESULT_INFL_osago',
             'EXPECTED_LOSS_PVU3_osago',
             'PVU_FREQ_osago',
             'PVU_SUMMATREBOVANII_osago',
             'PVU_SUMMAFIKS_osago',
             'PVU_SEGMENT_osago',
             'PVU_NULL_CLAIM_osago',
             'PVU_NULL_CLAIM_FREQ_osago',
             'PVU_EXPENSE_COUNT_osago',
             'PVU_EXPENSE_osago',
             'REFUND_FORM',
             'Сумма_износа_по_калькуляции_инцидент',
             'SEASON_WINTER_PRECIPITATION_AVG_MIN_osago',
             'SEASON_SPRING_PRECIPITATION_DEV_PERSENT_MIN_osago',
             'PREMIUM_COUNT_FUTURE_ALL',
#             'PREMIUM_SUM_ALL',
             'SEASON_SUMMER_PRECIPITATION_AVG_MAX_osago',
             'total_loss_osago',
             'LOSS_UNIT_DIVISION',
             'LOSS_STAGE',
             'FUTURE_PROLONGATION_osago',
             'SEASON_WINTER_TEMPERATURE_DEV_MAX_osago',
             'SEASON_SUMMER_TEMPERATURE_AVG_MAX_osago',
             'total_loss_pay_osago',
             'PAYMENT_TYPE',
             'SEASON_WINTER_TEMPERATURE_AVG_MIN_osago',
             'SEASON_WINTER_PRECIPITATION_NORMAL_osago',
             'REGION_CORRECTED',
             'PREMIUM_SUM_OSAGO',
             'LOSS_STATE_BY_IA',
             'REFUND_FORM_DETAILED',
             'EMRValue',
             'EMR_VALUE',
             'Взысканный_износ_ФУ',
             'REPAIR_VALUE',
             'AMOUNT_REPAIR',
             # AMOUNT_REPAIR-derived FE (заменены на VALUE_BEFORE_*)
             'FE_AMOUNT_REPAIR_BIN',
             'FE_HIGH_REPAIR',
             'FE_EXPECTED_WEAROUT_RUB',
             'FE_REPAIR_TO_VALUE_RATIO',
             'Выплаченный_износ_инцидент',
             # VALUE_BEFORE_WITH / VALUE_AFTER_WITH разрешаем (временно) для обучения
             'CHECK',
             # CPM/With related signals (leakage)
             'CPM_RATIO_RUB',
             'VALUE_AFTER_WITH',
             # refund / payment leakage (post-T0)
             'REFUND_FORM_BY_PAYMENT_ORDER',
             'FACT_AMOUNT_WITHOUT_OUTRUN',
             'FACT_AMOUNT_WITH_OUTRUN',
             'FE_REFUND_FORM_MATCH',
             'FE_REFUND_FORM_MISMATCH',
             'FE_REFUND_IS_CASH',
             'FE_REFUND_IS_REPAIR'],
 'BINARY': ['VICTIM_VEHICLE_IS_JAPAN']}

DEFAULT_OTHER_COLS: tuple[str, ...] = (
    'INCIDENT_NUMBER',
    'LOSS_NUMBER',
    'TARGET_2',
    'TARGET_FREQ',
    'TARGET_SEV',
    'TARGET_3_SEV',
    'TARGET_FREQ_AMOUNT',
    'TARGET_FREQ_CLAIMS_AMOUNT',
    'TARGET_FREQ_PRET_AMOUNT',
    'TARGET_SEV_CLAIMS_AMOUNT',
)